### ISSUE TITLE
Tecnicamente l'amount è sempre 1, non hai bisogno di passarlo da fuori.

### ISSUE THREAD

**Issue by lionhard83** [Vi-p1995/databaseProject#2]
https://github.com/Vi-p1995/databaseProject/blob/12c0418d9a4411b1f1863c4b5bdd2cdb2a35c687/routes/backOffice.js#L18

**Comment by Vi-p1995** [comment]
Se inserisco un prodotto... in questo modo ho la possibilità di inserire la quantità disponibile.
l'id l'ho crea in automatico, e io gli passo il nome, la descrizione e quanti pezzi ho disponibili.
poi la funzione è creata che se non passo il body mette undefined in product e description e in amount mette 0
