### ISSUE TITLE
arraySearch questa variabile non è definita da nessuna parte, forse dovrebbe essere tornata dalla libreria.

### ISSUE THREAD

**Issue by lionhard83** [Vi-p1995/databaseProject#3]
https://github.com/Vi-p1995/databaseProject/blob/12c0418d9a4411b1f1863c4b5bdd2cdb2a35c687/routes/backOffice.js#L41

**Comment by Vi-p1995** [comment]
devo revisionare il codice... siccome non ho messo l'export nelle variabili dell'npm relativo al database... cmq è funzionante... ritorna il mio array dichiarato dell'index.js dell'npm dbvi(il mio databse npm)
